DiamondLightSource/nexgen

src/nexgen/__init__.py
src/nexgen/beamlines/I24_Eiger_nxs.py
src/nexgen/nxs_write/NXclassWriters.py
src/nexgen/nxs_write/NexusWriter.py
src/nexgen/nxs_write/__init__.py

Fix 3.7 compatibility problems that came up on I24 and other issues like finding the correct file in the directory.
If possible, fix some gorillas.

Compatibility and other issues

---

src/nexgen/beamlines/I24_Eiger_nxs.py
src/nexgen/command_line/__init__.py
src/nexgen/command_line/copy_nexus.py
src/nexgen/command_line/nexus_generator.py
src/nexgen/command_line/nxs_phil.py
src/nexgen/command_line/phil_files_cli.py
src/nexgen/nxs_write/NXclassWriters.py
src/nexgen/nxs_write/NexusWriter.py
src/nexgen/nxs_write/data_tools.py

Just fixing some left over issues

New command line fixes 

---

src/nexgen/nxs_write/NXclassWriters.py
tests/test_NXclassWriters.py

Fixes #41
To test:
* Confirm new test is expected behaviour
* Confirm new test fails on main and pass on this branch

Fixed issue with module_offset depends on

---

.azure-pipelines/azure-pipelines.yml
setup.cfg
src/nexgen/command_line/__init__.py
src/nexgen/tools/GDAjson2params.py

Drop python3.6 support and add python 3.10

Remove python 3.6 support

---

src/nexgen/__init__.py
src/nexgen/beamlines/I03_Eiger.phil
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/beamlines/I24_Eiger_nxs.py
src/nexgen/beamlines/SSX_Tristan_nxs.py
src/nexgen/command_line/copy_nexus.py
src/nexgen/command_line/nexus_generator.py
src/nexgen/command_line/nxs_phil.py
src/nexgen/command_line/phil_files_cli.py
src/nexgen/nxs_copy/CopyTristanNexus.py
src/nexgen/nxs_write/NXclassWriters.py
src/nexgen/nxs_write/NexusWriter.py
src/nexgen/nxs_write/__init__.py
src/nexgen/tools/DataWriter.py
src/nexgen/tools/MetaReader.py
tests/test_tools.py
tests/test_write_tools.py

Now that more or less the basics are in main ...
Update I24 fixed target + option for copy from tristan in new PR.

Improve support for scans

---

src/nexgen/__init__.py
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/beamlines/I24_Eiger_nxs.py
src/nexgen/beamlines/SSX_Tristan_nxs.py
src/nexgen/command_line/copy_nexus.py
src/nexgen/command_line/nexus_generator.py
src/nexgen/command_line/phil_files_cli.py
src/nexgen/log.py
src/nexgen/nxs_copy/CopyNexus.py
src/nexgen/nxs_copy/CopyTristanNexus.py
src/nexgen/nxs_write/NXclassWriters.py
src/nexgen/nxs_write/NexusWriter.py
src/nexgen/tools/DataWriter.py
src/nexgen/tools/MetaReader.py
src/nexgen/tools/VDS_tools.py

Set up better logging

---

src/nexgen/beamlines/I24_Eiger_nxs.py
src/nexgen/beamlines/SSX_Tristan_nxs.py
src/nexgen/beamlines/__init__.py
src/nexgen/command_line/nexus_generator.py
src/nexgen/log.py
src/nexgen/nxs_copy/CopyTristanNexus.py
src/nexgen/nxs_copy/__init__.py
src/nexgen/nxs_write/NXclassWriters.py
src/nexgen/nxs_write/NexusWriter.py
src/nexgen/nxs_write/__init__.py

Close out a few tasks:
Documenting this also couldn't hurt ...

NeXus for fixed-target experiments

---

src/nexgen/tools/VDS_tools.py
tests/test_VDS_tools.py

Fixes #53
Allows you to specify the start index of the source for the VDS.
To test:
* Confirm unit tests pass
* Confirm no behavior changes by default

Added ability to specify non-zero indexed VDS

---

src/nexgen/tools/MetaReader.py
src/nexgen/tools/Metafile.py

Fix a couple of outstanding issues and add ability to open `config/` dataset.
Tidy up.

Meta file fixes

---

setup.cfg
src/nexgen/beamlines/I19_2_cli.py
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/nxs_write/NXclassWriters.py

I19-2 updates

---

.azure-pipelines/ci.yml

Update CI configuration

---

.codecov.yml
.readthedocs.yaml
CHANGELOG.md
pyproject.toml
requirements.txt
requirements_doc.txt

Add some configuration files

---

CHANGELOG.md
src/nexgen/nxs_write/NXclassWriters.py
tests/test_NXclassWriters.py

Optional information/logging added.

NXclass writers tweaks

---

CHANGELOG.md
src/nexgen/beamlines/SSX_Tristan_nxs.py
src/nexgen/nxs_copy/CopyTristanNexus.py
src/nexgen/nxs_copy/__init__.py
tests/test_copy_tools.py

Close outstanding tasks relating to SSX with Tristan 10M.
Closes #76.

SSX Tristan copy for binned images

---

CHANGELOG.md
docs/api.rst
src/nexgen/command_line/ED_nexus.py
src/nexgen/templates/ED_Singla.phil
src/nexgen/tools/DataWriter.py
src/nexgen/tools/ED_tools.py
tests/test_tools_for_ED.py

This PR adds a simple algorithm to identify the direct beam centre from a SINGLA dataset prior to conversion to `.nxs`.

Find SINGLA direct beam centre

---

src/nexgen/beamlines/I24_Eiger_nxs.py

Redefine chipmapfile

---

CHANGELOG.md
docs/usage.rst
src/nexgen/command_line/ED_nexus.py

Add an argument to the parser in order to be able to save the NeXus file in another location in case of writing permission issues.
The downside of this is that the links to the data files will be absolute instead of relative.

Singla output

---

CHANGELOG.md
src/nexgen/beamlines/I19_2_cli.py
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/nxs_write/NexusWriter.py

Super messy - to be fixed after Feb 1st.

Hotfix for serial on I19-2 with Eiger

---

CHANGELOG.md
src/nexgen/beamlines/I24_Eiger_nxs.py
src/nexgen/beamlines/SSX_chip.py

Fix 'up' blocks start and end positions for SSX

---

.azure-pipelines/azure-pipelines.yml
.azure-pipelines/ci.yml
.pre-commit-config.yaml
.readthedocs.yaml
CHANGELOG.md
setup.cfg
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/beamlines/SSX_chip.py
src/nexgen/command_line/I19_2_cli.py
src/nexgen/tools/ED_tools.py
src/nexgen/tools/Metafile.py

Drop python3.7 support and add python3.11

Remove python 3.7 support

---

.readthedocs.yaml
requirements_doc.txt

- Update config file for readthedocs
- Update sphinx packages versions

Update documentation config 

---

src/nexgen/nxs_utils/Detector.py

adds the `bit_depth_image` field

add link in detector definition

---

src/nexgen/beamlines/I19_2_gda_nxs.py
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/beamlines/I19_2_params.py
src/nexgen/beamlines/I24_Eiger_params.py
src/nexgen/beamlines/SSX_Eiger_nxs.py
src/nexgen/beamlines/__init__.py
src/nexgen/tools/MetaReader.py
src/nexgen/tools/Metafile.py
tests/tools/test_meta_tools.py

Fix ssx eiger dtype issue

---

CHANGELOG.md
src/nexgen/beamlines/I19_2_params.py
src/nexgen/beamlines/I24_Eiger_params.py
src/nexgen/nxs_utils/Detector.py
src/nexgen/nxs_write/NXmxWriter.py

Temporary bit_depth fixes

---

src/nexgen/nxs_utils/Goniometer.py

Needed for https://github.com/DiamondLightSource/python-artemis/issues/370 / https://github.com/DiamondLightSource/python-artemis/pull/697

update gonio from scan on init (if supplied) 

---

CHANGELOG.md
src/nexgen/nxs_utils/Detector.py
src/nexgen/nxs_utils/__init__.py
src/nexgen/nxs_write/NXclassWriters.py
src/nexgen/nxs_write/NXmxWriter.py
tests/nxs_utils/test_detector.py

Adds some detector constants for the Jungfrau M1.

Add jungfrau

---

CHANGELOG.md
docs/usage.rst
src/nexgen/beamlines/ED_params.py
src/nexgen/nxs_utils/Detector.py
src/nexgen/nxs_utils/Source.py
src/nexgen/nxs_utils/__init__.py
src/nexgen/templates/ED_Singla.phil
src/nexgen/utils.py
tests/nxs_utils/test_detector.py
tests/nxs_utils/test_source.py

Use `Electron Source` as source type for ED

---

CHANGELOG.md
src/nexgen/command_line/SSX_cli.py
src/nexgen/command_line/cli_utils.py
tests/beamlines/test_SSX_chip.py

Fix SSX_cli import issue

---

CHANGELOG.md
src/nexgen/nxs_write/NXclassWriters.py
tests/nxs_write/test_NXclassWriters.py

Closes #138 
Creates a soft link in /entry/instrument/detector to /entry/instrument/detector/transformations/detector_z

Add detector_z in NXdetector

---

CHANGELOG.md
src/nexgen/beamlines/I19_2_gda_nxs.py
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/beamlines/SSX_Eiger_nxs.py
src/nexgen/beamlines/SSX_Tristan_nxs.py
src/nexgen/command_line/ED_nexus.py
src/nexgen/command_line/cli_utils.py
src/nexgen/command_line/nexus_generator.py
src/nexgen/nxs_write/NXclassWriters.py
src/nexgen/nxs_write/NXmxWriter.py
src/nexgen/nxs_write/write_utils.py
src/nexgen/utils.py
tests/nxs_write/test_NXclassWriters.py
tests/nxs_write/test_NXmxWriter.py

Write end_time_estimated field

---

CHANGELOG.md
src/nexgen/beamlines/ED_params.py
src/nexgen/beamlines/ED_singla_nxs.py
src/nexgen/beamlines/beamline_utils.py
src/nexgen/command_line/ED_nexus.py
src/nexgen/nxs_utils/Source.py
src/nexgen/nxs_write/NXclassWriters.py
src/nexgen/nxs_write/NXmxWriter.py
src/nexgen/nxs_write/write_utils.py
src/nexgen/tools/ED_tools.py
src/nexgen/utils.py
tests/nxs_write/test_NXclassWriters.py
tests/test_utils.py

- A more general writer for singla data
-  A small cli which doens't need phil parsers

General changes in singla writer

---

CHANGELOG.md
src/nexgen/nxs_write/NXclassWriters.py
src/nexgen/nxs_write/write_utils.py
src/nexgen/tools/ED_tools.py
tests/nxs_write/conftest.py
tests/nxs_write/test_NXclassWriters.py
tests/nxs_write/test_write_utils.py
tests/tools/test_tools_for_ED.py

Tidy up and split into different functions
Spin off from #184 , should fix it and close it.

Refactor mask and flatfield writing

---

CONTRIBUTING.rst
pyproject.toml

- Write an improved version of CONTRIBUTING.md
- Update ruff options in pyproject and add dependency

Package updates

---

CHANGELOG.md
src/nexgen/nxs_write/NXclassWriters.py
tests/nxs_write/test_NXclassWriters.py

Change data_size, as well as a couple ofthers, dtype to native int (uint32)

Change dtypes to native int

---

src/nexgen/nxs_utils/Detector.py
src/nexgen/nxs_write/NXclassWriters.py

Would like to merge https://github.com/DiamondLightSource/nexgen/pull/220 first.
Fixes the immediate issue in #219 but doesn't yet add tests comparing nexgen to GDA files

219 add detectorspecific fields

---

CHANGELOG.md
docs/api_beamlines.rst
src/nexgen/beamlines/I19_2_gda_nxs.py
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/beamlines/SSX_Eiger_nxs.py
src/nexgen/beamlines/SSX_Tristan_nxs.py
src/nexgen/beamlines/SSX_expt.py
src/nexgen/beamlines/beamline_utils.py
src/nexgen/nxs_copy/copy_utils.py
tests/beamlines/test_SSXwriters.py
tests/beamlines/test_beamline_utils.py

Tidy up parameters in beamlines scripts

---

CHANGELOG.md
src/nexgen/beamlines/SSX_Eiger_nxs.py
src/nexgen/nxs_utils/detector.py
src/nexgen/nxs_write/nxclass_writers.py
tests/beamlines/test_SSXwriters.py

Closes #266 
- Refactors the code a bit
- Remove reading of meta file

Do not read meta file for SSX

---

docs/api_beamlines.rst
docs/conf.py

Some fields and functions not rendering correctly on readthedocs.

Fix docs issues

---

src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/nxs_write/nxmx_writer.py

In case the meta file and nexus file have different filenames

Add image_filename to event writer

---

CHANGELOG.md
src/nexgen/beamlines/I19_2_nxs.py

Add possibility for writing an NXnote to I19-2 writers, so eg. well number is saved there instead of filename

Add notes for I19 collections

---

pyproject.toml

Pin flexparser

---

CHANGELOG.md
pyproject.toml
requirements_doc.txt
src/nexgen/utils.py

Add a small utility to create directories

---

CHANGELOG.md
src/nexgen/nxs_utils/source.py
src/nexgen/nxs_write/nxclass_writers.py
tests/nxs_utils/test_source.py
tests/nxs_write/conftest.py
tests/nxs_write/test_NXclassWriters.py

Allow list of wavelengths

---

CHANGELOG.md
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/nxs_utils/sample.py
src/nexgen/nxs_write/nxclass_writers.py
src/nexgen/nxs_write/nxmx_writer.py
tests/nxs_utils/test_sample.py
tests/nxs_utils/test_scan.py

Closes #354 
- Better definition of Sample
- Added sample as optional argument to NXmx writers
- NXsample depends_on dataset can now be set by passing Sample(depends_on="axisname") to writers.

Improve sample definition and set NXsample depends on
