DiamondLightSource/nexgen

src/nexgen/command_line/copy_nexus_from_tristan.py
src/nexgen/copy/CopyTristanNexus.py

- Allow specification of write mode for output NeXus file.
- Remove unnecessary file read.  When creating an h5py ExternalLink, it is not necessary to hold the target open for reading.
- When making NeXus output, return output file name.

Refinements to enable NeXus files for Tristan image data

---

src/nexgen/copy/CopyTristanNexus.py

Some early Tristan data recorded before March 2021, and where the goniometer was not moved during the data collection, record the rotation axis position as a scalar, whereas we expect it always to be a tuple.
Introduce some exception handling to be more accepting of this legacy data format.

Handle TypeErrors and ValueErrors from legacy data

---

.azure-pipelines/ci.yml

- Migrate from [the deprecated Codecov Bash uploader](https://docs.codecov.com/docs/about-the-codecov-bash-uploader#deprecation-notice-and-schedule) to [the new pre-built binary uploader](https://docs.codecov.com/docs/codecov-uploader).
- Use the Codecov token, saved as a secret-value variable in the Azure pipeline.  Strictly, [this ought not to be needed](https://docs.codecov.com/docs/codecov-uploader#upload-token), but in practice it seems to be necessary.

Use the Codecov uploader

---

MANIFEST.in
src/nexgen/beamlines/I24_Eiger.phil
src/nexgen/beamlines/I24_Eiger_nxs.py
src/nexgen/beamlines/I24_Eiger_params.py
src/nexgen/command_line/nexus_generator.py
src/nexgen/command_line/nxs_phil.py
src/nexgen/nxs_write/NXclassWriters.py
src/nexgen/nxs_write/data_tools.py

While the nexus file writing works fine (so far, test with beam tbd), a few outstanding issues have been identified during the latest test.
TODO list:

Fix outstanding extruder issues

---

requirements_dev.txt
setup.cfg
src/nexgen/__init__.py
src/nexgen/beamlines/I19-2_Eiger.phil
src/nexgen/beamlines/I19-2_Tristan.phil
src/nexgen/beamlines/I24_Eiger.phil
src/nexgen/beamlines/I24_Eiger_nxs.py
src/nexgen/command_line/__init__.py
src/nexgen/command_line/nexus_generator.py
src/nexgen/command_line/nxs_phil.py
src/nexgen/command_line/phil_files_cli.py
src/nexgen/nxs_write/NXclassWriters.py

There are a couple of things to be checked to make sure that the command line tools work well in general. (as of 0.5.11 it looks like they do the job with a few quirks)
There is also a need for a way to generate the nexus file from the command line if something goes wrong during the collection, asap for I24.

Command line fixes

---

.pre-commit-config.yaml
docs/conf.py
src/nexgen/__init__.py
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/beamlines/I24_Eiger_nxs.py
src/nexgen/beamlines/SSX_Tristan_nxs.py
src/nexgen/command_line/__init__.py
src/nexgen/command_line/copy_nexus.py
src/nexgen/command_line/nexus_generator.py
src/nexgen/command_line/phil_files_cli.py
src/nexgen/nxs_copy/CopyNexus.py
src/nexgen/nxs_copy/CopyTristanNexus.py
src/nexgen/nxs_copy/__init__.py
src/nexgen/nxs_write/NXclassWriters.py
src/nexgen/nxs_write/NexusWriter.py
src/nexgen/nxs_write/__init__.py
src/nexgen/tools/DataWriter.py
src/nexgen/tools/ExtendedRequest.py
src/nexgen/tools/GDAjson2params.py
src/nexgen/tools/MetaReader.py
src/nexgen/tools/Metafile.py
src/nexgen/tools/VDS_tools.py
tests/test_NXclassWriters.py
tests/test_tools.py
tests/test_write_tools.py

Avoid mis-identifying HDF5 dataset objects under `/entry/data` as the scan axis data set unless they have the appropriate `transformation_type` attribute.
- Avoid mis-identifying the scan axis data set under `/entry/data` by  explicitly checking for the `transformation_type` attribute.
- Ensure that the return value of `identify_tristan_scan_axis` is always  defined.
- Specify return types.
- Allow for the possibility that there is no scan axis recorded in  `/entry/data`.
- Make miscellanous houskeeping changes.

Be more prescriptive in finding the scan axis

---

src/nexgen/tools/VDS_tools.py
tests/test_VDS_tools.py

Does the following:
* Gives a nicer warning if no dataset links are found in the NeXus file
* Casts VDS shapes and index starts to ints (with a warning)
To test:
* Run new tests and confirm they pass

Add some more edge case handling to VDS writer

---

src/nexgen/command_line/__init__.py
src/nexgen/command_line/copy_nexus.py
src/nexgen/command_line/nexus_generator.py
src/nexgen/command_line/phil_files_cli.py

In the CLI the -c/-a options are broken with some subcommands. 
In particular they seem to be problematic for `generate_nexus 2`, while `generate_nexus -c -a 2 3` does exactly what it's supposed to. 
It's also not entirely clear how to use them from looking at argparse --help. They appear in the main one but won't work without the subcommand.
It's probably best to have a separate parser with these options which can be added as parent to each subparser (also avoids repetition in the different CL scripts).

Fix show-config in parser

---

src/nexgen/__init__.py
src/nexgen/nxs_copy/CopyNexus.py
src/nexgen/nxs_copy/CopyTristanNexus.py

There's an issue when simply copying metadata from one file to a new one. 
At the moment the function tries to create a new NeXus file with the same name as the original one, leading to OSError.
This is not an issue with the Tristan functions.

Fix general copy functions

---

src/nexgen/beamlines/I19_2_gda_nxs.py
src/nexgen/nxs_write/NXclassWriters.py

Fix plugin issue when copying mask and flatfield by importing filter before h5py. This should get it to find the correct plugins to write the datasets.

Fix mask and flatfield writing

---

CHANGELOG.md
src/nexgen/beamlines/I24_Eiger_nxs.py
src/nexgen/beamlines/SSX_chip.py
tests/test_SSX_chip.py

Following test on beamline, a couple of fixes/improvements:
Fixing this might help issue #55 .

I24 SSX fixed target fixes

---

CHANGELOG.md
src/nexgen/tools/VDS_tools.py
tests/test_VDS_tools.py

In `VDS_tools.split_datasets()`, checks if the dataset is actually used in the VDS before adding it to the list so that unused datasets are not used as sources for the VDS
And adds a function to clean any linked datasets which are not used in the VDS

#87 Don't use unused datasets as VDS source

---

CHANGELOG.md
src/nexgen/beamlines/I19_2_gda_nxs.py
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/nxs_write/NXclassWriters.py
src/nexgen/nxs_write/NexusWriter.py

As a result of changing the way sample_depends_on is written, I19-2 wasn't updated and points to `sam_x` instead of `phi` for the sample depends_on field (`entry/sample/depends_on`).

I19-2 nexus fixes

---

src/nexgen/tools/VDS_tools.py

So, it seems that Singla datasets have maxshape set to None, and there is no maximum of 1000 frames per file. However the VDS writer assumes this when splitting the datasets and for a longer singla collection every frame with a higher index is not included in the vds
eg. for what should be a 1200 frame collection : 
```Grey-Area work :( $ h5ls -rv ../20230110_1406_nav66_-64.187.93._120DEG_10FPS_50c2.nxs/entry/data/data
Opened "../20230110_1406_nav66_-64.187.93._120DEG_10FPS_50c2.nxs" with sec2 driver.
entry/data/data          Dataset {1000/1000, 1062/1062, 1028/1028}
Location:  1:2973892
Links:     1
Maps:      {1} Source {
.   /entry/data/data_000001
}
Storage:   2183472000 logical bytes, 0 allocated bytes
Type:      native unsigned short```

Singla VDS hack

---

CHANGELOG.md
requirements.txt
requirements_dev.txt
requirements_doc.txt
setup.cfg
src/nexgen/nxs_write/__init__.py

Fix the following warning when writing a compressed copy of the pixel mask or flatfield, due to changes in the latest version of `hdf5plugin`.
```Deprecation: hdf5plugin.Bitshuffle's lz4 argument is deprecated, use cname='lz4' or 'none' instead.```

Fix bitshuffle deprecation warning 

---

CHANGELOG.md
docs/api.rst
src/nexgen/nxs_copy/CopyTristanNexus.py

Change input for `single_image_nexus` from bool to number of bins. This is because python-tristan writes the nexus file before binning so there won't be any data file to look at for the shape.

Tristan copy pp small fix

---

CHANGELOG.md
src/nexgen/beamlines/SSX_chip.py
src/nexgen/beamlines/SSX_expt.py
tests/beamlines/test_SSX_chip.py
tests/beamlines/test_SSX_expt.py

There's a miscalculation in the oscillation axis (omega) end values for upwards blocks of the chip. 
Also useful to add a conversion between chip coordinates and block number to avoid errors when using a fullchip.

Keep the osc axis constant in fixed target for SSX

---

.pre-commit-config.yaml
CHANGELOG.md
setup.cfg
src/nexgen/beamlines/SSX_Eiger_nxs.py

In order to be able to start writing the nexus file at the beginning of a serial collection, avoid looking for the physical files in the directory and generate the list of data file names from the expected total number of images.

SSX Eiger data file list improvement

---

.pre-commit-config.yaml
CHANGELOG.md
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/beamlines/SSX_Eiger_nxs.py
src/nexgen/command_line/nexus_generator.py
src/nexgen/nxs_write/NexusWriter.py
src/nexgen/tools/MetaReader.py
src/nexgen/tools/Metafile.py
tests/test_VDS_tools.py
tests/test_meta_tools.py

To enable running nexgen during data collection. ODIN has the file open for writing in SWMR mode for the duration of data collection.
Read config items from `/_dectris/` instead of `/config/` - the former should be accessible when read in SWMR mode during data collection whereas the latter is added dynamically and isn't accessible until the file is no longer open for writing

Support reading metafile in SWMR mode

---

CHANGELOG.md
src/nexgen/nxs_write/NXmxWriter.py

Make clean up of unused links in VDS optional.
Set to False by default.

Optional vds clean up

---

CHANGELOG.md
src/nexgen/command_line/SSX_cli.py
src/nexgen/command_line/cli_utils.py
src/nexgen/templates/I19-2_Eiger.phil
src/nexgen/templates/I19-2_Tristan.phil
tests/beamlines/test_SSX_chip.py

Mark Warren reported an error when using `generate_nexus`:
```
ERROR - Number of axes 6 doesn't match the lenght of the array list 21.Please check again and make sure that all axes have a matching array of size 3.
```
Tracked down the issue to his phil file having too many values in the goniometer.offset - and this came straight from the template. So I propose we need to reduce the number of 0s in the offset, but I'm not an expert on this so treat this as a discussion topic :smile:

reduce number of offsets from i19 phil templates

---

CHANGELOG.md
docs/api_beamlines.rst
docs/usage.rst
src/nexgen/beamlines/I19_2_gda_nxs.py
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/beamlines/I19_2_params.py
src/nexgen/beamlines/I24_params.py
src/nexgen/beamlines/SSX_Eiger_nxs.py
src/nexgen/beamlines/SSX_Tristan_nxs.py
src/nexgen/beamlines/beamline_utils.py
src/nexgen/command_line/I19_2_cli.py
src/nexgen/nxs_utils/Detector.py
src/nexgen/nxs_write/NXmxWriter.py
src/nexgen/nxs_write/write_utils.py
tests/beamlines/test_SSXwriters.py
tests/beamlines/test_i19nxs.py
tests/nxs_write/test_write_utils.py

Closes #142 
The non-gda I19 writer for Eiger should have the option of not using the meta file to update axis/beam/etc... information but get them from input arguments.
The data type for the vds in this case should be set as native int.

Refactor I19 writer to avoid meta file

---

src/nexgen/beamlines/ED_singla_nxs.py
src/nexgen/command_line/ED_nexus.py
src/nexgen/tools/ED_tools.py

Hello,
I hope this resolves the issue. I've added a function `get_data_collection_date` to `SinglaMaster` class. I then read the date into the dictionary in `extract_from_Singla_master`. It seems that this function is more related to detector parameters so I don't know should the collection date go there. 
The date and time are saved in `params.start_time`. I am assuming the start time from the command line goes to this variable. So, if there is no `start_time`, the script will get that data from the master file. In the end, I pass the `params.start_time` as an argument to the writer function.
I checked this and it works when converting original master and data files on my laptop.

Read data_collection_date from master file as start_time

---

CHANGELOG.md
src/nexgen/nxs_utils/Goniometer.py
tests/nxs_utils/test_goniometer.py
tests/nxs_write/test_NXclassWriters.py

Fixes a bug in the `Goniometer`, where in case of a reverse rotation the `Axis` start_pos and increment were updated in the wrong way, leading to the wrong values for `axis_end` in `NXsample`.

Fix axis_end values for reverse rotation scans

---

CHANGELOG.md
src/nexgen/nxs_copy/CopyTristanNexus.py
src/nexgen/nxs_copy/copy_utils.py
tests/nxs_copy/test_copy_tools.py

Fixes #170 
Writes the optional axes fields `axis_increment_set` and `axis_end` for tristan binned data.

Add optional axis fields for tristan

---

src/nexgen/nxs_utils/Detector.py

Fixes #178 
To test:
* Confirm test still pass and type errors are reduced

Fix various type hints around the detector

---

src/nexgen/nxs_write/NXclassWriters.py

Fixes #186 
Adds these extra fields because AutoPROC wants them

#186 Add {x,y}_pixels_in_detector

---

CHANGELOG.md
src/nexgen/beamlines/ED_params.py

In the beamline parameters for electron diffraction, the rotation axis vector is wrong. 
This value should be `0,-1,0`

Fix rotation axis vector for electron diffraction

---

CHANGELOG.md
src/nexgen/__main__.py
src/nexgen/log.py
src/nexgen/nxs_copy/copy_nexus.py
src/nexgen/nxs_write/nxclass_writers.py
src/nexgen/nxs_write/nxmx_writer.py
src/nexgen/nxs_write/write_utils.py
src/nexgen/tools/meta_reader.py
src/nexgen/tools/vds_tools.py
tests/test_log.py

Closes #194 
- Sets the logging level for the StreamHandler to INFO
- Sends all debug messages only to the file, when configured.
- Sets logs from NXclass writers/ Nexus writer to DEBUG to avoid overly chatty logs.

Make logs less chatty

---

CHANGELOG.md
pyproject.toml
src/nexgen/nxs_copy/copy_utils.py
src/nexgen/nxs_write/nxclass_writers.py
src/nexgen/nxs_write/write_utils.py
src/nexgen/tools/data_writer.py
src/nexgen/tools/mrc_tools.py
tests/nxs_write/conftest.py

In numpy 2.0 the `numpy.string_` alias for `numpy.bytes_` has been deprecated. This alias was used to write fixed-width bytestrings to h5 files in multiple places in the codebase. Replace with `numpy.bytes_` to avoid compatibility issues and to tidy up.

Make code compatible with both numpy 2.0 and earlier

---

CHANGELOG.md
src/nexgen/nxs_utils/detector.py
src/nexgen/nxs_write/nxclass_writers.py

Closes #236 
The string format issue in the meta file has been fixed in [eiger-detector version1.15.1](https://github.com/dls-controls/eiger-detector/releases/tag/1.15.1)

Re-enable external links for eiger meta file

---

CHANGELOG.md
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/beamlines/SSX_expt.py
src/nexgen/beamlines/beamline_utils.py
src/nexgen/command_line/I19_2_cli.py
src/nexgen/nxs_copy/copy_utils.py
src/nexgen/utils.py
tests/beamlines/test_beamline_utils.py
tests/beamlines/test_i19nxs.py
tests/test_utils.py

- Improve the parameter model
- Add small wrapper function to be used by nexgen-server
- Update CLI
- Fix small bug with timestamps
- Refactor deprecated functions

Updates for I19 serial

---

CHANGELOG.md
pyproject.toml
requirements_doc.txt
src/nexgen/beamlines/I19_2_nxs.py
src/nexgen/beamlines/SSX_expt.py
src/nexgen/beamlines/beamline_utils.py
src/nexgen/command_line/ED_mrc_to_nexus.py
src/nexgen/command_line/I19_2_cli.py
src/nexgen/nxs_copy/copy_utils.py
src/nexgen/nxs_utils/__init__.py
src/nexgen/nxs_utils/detector.py
src/nexgen/tools/mrc_tools.py
src/nexgen/utils.py
tests/beamlines/test_beamline_utils.py
tests/beamlines/test_i19nxs.py
tests/test_utils.py
tests/tools/test_mrc_tools.py

Extend ED_mrc_to_nexus command to work with TVIPS cameras (besides eBIC Ceta-D detector). The command now has an option --detector that could be set either to cetad or tvips.

Extend MRC to Nexus converter to work with TVIPS
